security:
  encoders:
    App\Entity\User:
      algorithm: auto
  providers:
    user_doctrine:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      remember_me:
        secure: true
        lifetime: 604800
        secret: '%kernel.secret%'
        path: /
        samesite: lax
      lazy: true
      provider: user_doctrine
      guard:
        authenticators:
          - App\Security\Guard\WebAuthenticator
      logout:
        path: security_logout

  role_hierarchy:
    ROLE_PRODUCER: [ ROLE_USER ]
    ROLE_CUSTOMER: [ ROLE_USER ]

  access_control:
