framework:
  workflows:
    order:
      type: 'state_machine'
      audit_trail:
        enabled: true
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - App\Entity\Order
      initial_marking: created
      places:
        - created
        - refused
        - accepted
        - settled
        - canceled
        - processing
        - ready
        - issued
      transitions:
        cancel:
          from: [ created, accepted ]
          to: canceled
        refuse:
          from: created
          to: refused
        accept:
          from: created
          to: accepted
        settle:
          from: accepted
          to: settled
        process:
          from: settled
          to: processing
        ready:
          from: processing
          to: ready
        deliver:
          from: ready
          to: issued
